Front: PasswordResetView
schmidti2002/Softwarepraktikum pull request #112
Opened 2024-03-01 17:31 UTC by Agent-Lucky

Implementierung von PasswordResetView.html/js und Hinzufügen der Email-Validierung in inputValidator.js

2024-03-04 01:00 UTC, ps100000 requested changes

2024-03-04 01:00 UTC, ps100000 commented on Meilensteine/Meilenstein_04/frontend/src/inputValidators.js
> +  }
```suggestion
  }
  return 'Ungültige E-Mail-Adresse'; // Die E-Mail-Adresse ist ungültig
```
Nur ne Kleinigkeit :)

2024-03-05 16:26 UTC, Agent-Lucky commented on Meilensteine/Meilenstein_04/frontend/src/PasswordResetView.js
> +            const user = await UserApi.userGet({ username, email });
Wie oder besser wo schreibe ich die Erweiterung für die Spezifikation. Ich hätte sie jetzt mit meinem Laienwissen in userApi.ts geschrieben. Aber dort steht explizit "is autogenerated" und "Do not edit the class manually."

2024-03-05 19:12 UTC, Agent-Lucky commented on specs/openapi/openapi.yaml
> +          description: user with email not found
Kritisch? Habe so das Gefühl, dass das dem Datenschutz nicht gerade dient.

2024-03-05 22:17 UTC, ps100000 approved these changes

2024-03-05 22:22 UTC, merged