Front merge sort
schmidti2002/Softwarepraktikum pull request #113
Opened 2024-03-02 07:53 UTC by NociCreep

2024-03-02 07:58 UTC, NociCreep commented on Meilensteine/Meilenstein_04/frontend/src/MergeSortLogic.js
> +      [21],
Vielleicht will man mehr Breakpoints sehen

2024-03-02 07:58 UTC, NociCreep commented on Meilensteine/Meilenstein_04/frontend/src/MergeSortLogic.js
> +      [21],
Ich hatte auch mal den Timeout höher gestellt, also ich bin mir nicht sicher ob das MergeSort so korrekt, weil ich es eben in paar Schritten durchläuft. 
Sonst sieht aber alles gut aus.

2024-03-02 09:48 UTC, NociCreep commented
> Theoretisch müsste man natürlich noch einen Test schreiben. Wenn man sich an BubbleSort orientiert geht das vielleicht zügig

Habe ich mal gemacht, unter anderem auch noch was für BubbleSort.

2024-03-02 14:15 UTC, thori2t commented on Meilensteine/Meilenstein_04/frontend/src/MergeSortLogic.js
> +      [21],
Ich verstehe was dein Problem ist. Der Algorithmus sieht nicht ganz aus, wie klassisches (rekursives) Merge Sort. Das liegt daran, dass in unserer Programmiersprache in der Programmiersprache keine Rekursion möglich ist (was ja auch nicht schlimm ist). Deshalb ist das kein rekursiver sondern iterativer Merge Sort. Wenn man die Anzahl der Beispiele auf 2^x stellt (z.B. 16) dann sieht man sehr gut, dass es Merge Sort ist. Da ist 10 eine unpassende Anzahl an Sortierungen.

2024-03-04 01:04 UTC, ps100000 requested changes

2024-03-04 01:04 UTC, ps100000 commented on Meilensteine/Meilenstein_04/frontend/test/__snapshots__/DataView.test.js.snap
> -exports[`DataView Snapshot Tests snapshot with array data 1`] = `"<div><div class="dataview-type-object"><div class="d-flex">0:<div class="dataview-type-string">one</div></div><div class="d-flex">1:<
warum hast du die gelöscht?

2024-03-04 07:46 UTC, merged