Kommentare
schmidti2002/Softwarepraktikum pull request #115
Opened 2024-03-02 12:28 UTC by NociCreep

2024-03-03 12:49 UTC, thori2t approved these changes
Super

2024-03-04 00:52 UTC, ps100000 requested changes

2024-03-04 00:52 UTC, ps100000 commented on Meilensteine/Meilenstein_04/frontend/src/AlgoExecuter.js
> +  // gibt wahr zurück, wenn der Algorithmus läuft
Nein! Doch! Ohh! 😜 
( Kommentare sollten nützliche Infos enthalten. Was istRunning tut sollte der Name eigentlich schon verraten )

2024-03-04 00:52 UTC, ps100000 commented on Meilensteine/Meilenstein_04/frontend/src/CodeView.js
> +  // wird in loadAlgoByIndex(index) in AuDView.js aufgerufen
Diese Art von Kommentaren sind zwar gut gemeint aber unglaublich schwer zu pflegen

2024-03-04 00:52 UTC, ps100000 commented on Meilensteine/Meilenstein_04/frontend/src/CodeView.js
> +  // zeigt vermutlich die aktuelle Position im Code an???
ja

2024-03-04 00:52 UTC, ps100000 commented on Meilensteine/Meilenstein_04/frontend/src/InputView.js
> +  // parst ein Integer und gibt ihn als {value: Integer} zurück
Dieser und andere Kommentare enthalten nur die Hälfte der Wahrheit.
Hier fehlt: Im Fehlerfall wird {error: 'reason'} zurückgegeben.

2024-03-04 00:52 UTC, ps100000 commented on Meilensteine/Meilenstein_04/frontend/src/CodeView.js
> +  // zeigt die Breakpoint, in breakpoints in algo in algos[] der Logikklassen gespeichert, an
Nach diesem Kommentar war ich mehr verwirrt als davor. Überprüf vielleicht nochmal deine Formulierungen.

2024-03-04 07:29 UTC, merged